<?php

/**
 * @category    Pademobile
 * @package     Pademobile_Pademobile
 * @copyright   Copyright (c) Pademobile International, LLC (https://www.pademobile.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * redirect.phtml
 *
 * @author Pademobile Development Team
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Your about to be redirected to Pademobile payment gateway') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__("You'll be redirected in <span id='redirect_seconds'>5</span> seconds") ?></h2>
<p><?php echo $this->__("Or Click \"Submit\" if you don't wish to wait."); ?></p>
<form name="pademobile" id="pademobile" action="<?php echo $this->getFormActionUrl(); ?>" method="post">
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var pademobile = new Pademobile();
//]]>
</script>