<script
	src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script type="text/javascript">
	
	$j = jQuery.noConflict();
	$j( document ).ready(function() {
		$j("#review_button").trigger("click");
	});

	
</script>
<style type="text/css">
#backgr {
	background-color: #EFEFEF;
	display: inline;
	bottom: 0;
	height: 100%;
	left: 0;
	position: fixed;
	right: 0;
	top: 0;
	width: 100%;
	z-index: 980;
}
#ppmx_popup {
	z-index: 1001;
	display: inline;
	width: 400px;
	height: 300px;
	position: fixed;
	top: 50%;
	left: 50%;
	margin: -200px 0 0 -200px;
	line-height: normal;
	background: #fefefe; /* Old browsers */
	background: -moz-linear-gradient(top, #fefefe 0%, #f1f2f4 100%);
	/* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fefefe),
		color-stop(100%, #f1f2f4)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top, #fefefe 0%, #f1f2f4 100%);
	/* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top, #fefefe 0%, #f1f2f4 100%);
	/* Opera 11.10+ */
	background: -ms-linear-gradient(top, #fefefe 0%, #f1f2f4 100%);
	/* IE10+ */
	background: linear-gradient(to bottom, #fefefe 0%, #f1f2f4 100%);
	/* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient(   startColorstr='#fefefe',
		endColorstr='#f1f2f4', GradientType=0); /* IE6-9 */
}

#ppmx_popup .ppmx_logo {
	float: right;
	margin: 10px;
}

#ppmx_popup .ppmx_content {
	margin-top: 80px;
}

#ppmx_popup .ppmx_loader {
	display: block;
	margin: 20px 0 0 0px;
}

#ppmx_popup .ppmx_loader div {
	color: #0071BB;
	font-size: 10px;
	text-align: center;
}

#ppmx_popup .ppmx_loader img {
	position: relative;
	left: 50%;
	margin: 0 0 15px -105px;
}

#ppmx_popup .ppmx_title {
	font-size: 25px;
	color: #0F4073;
}

#ppmx_popup .ppmx_box {
	margin: 0 10px 0 0;
	float: left;
	width: 50px;
	height: 100px;
	background: #0079C0;
	-webkit-border-top-right-radius: 6px;
	-webkit-border-bottom-right-radius: 6px;
	-moz-border-radius-topright: 6px;
	-moz-border-radius-bottomright: 6px;
	border-top-right-radius: 6px;
	border-bottom-right-radius: 6px;
}
</style>
<div id="backgr"></div>
<div id='ppmx_popup'>
	<img style="width: 125px; height: 44px"
		src="<?php echo $this->getSkinUrl('images/paypalmx/bdg_compra_segura_pp_.PNG'); ?>"
		class='ppmx_logo'>
	<div class='ppmx_content'>
		<div class='ppmx_box'></div>
		<span class='ppmx_title'>Espere mientras procesamos su pago.</span></br>
		<div class='ppmx_loader'>
			<img alt="" src="<?php echo $this->getSkinUrl('images/paypalmx/paypalmx_loader.gif');?>" style = "height: 100px; width: 100px;">
		</div>
	</div>
</div>
<?php
$billingBlock = $this->getChild('billing')->setFieldNamePrefix('billing')->setHideEmailAddress(true);
$shippingAddress = $this->getShippingAddress();
?>
<div class="page-title">
    <h1><?php echo $this->__('Review Order') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<script type="text/javascript">
//<![CDATA[
    var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>
//]]>
</script>
<h2 class="sub-title">
    Please confirm your addresses
</h2>
<div class="paypal-review-order">
    <form method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
    <?php if(!$billingBlock->isCustomerLoggedIn()): ?>
        <div class="info-set col2-set">
            <h2 class="legend"><?php echo $this->__('Customer Information') ?></h2>
            <ul class="form-list form-list-narrow">
                <li id="customer-info-form" class="address-form">
                    <div class="field">
                        <label for="customer:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="customer-email" id="customer:email" value="<?php echo $this->escapeHtml($billingBlock->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    <?php endif ?>
    <div class="info-set col2-set">
        <div class="col-1" id="billing-address">
            <h2 class="legend"><?php echo $this->__('Billing Address') ?></h2>
            <?php if ($shippingAddress): ?>
                <?php echo $billingBlock->setShowAsShippingCheckbox(true)->toHtml(); ?>
            <?php else: ?>
                <?php echo $billingBlock->toHtml(); ?>
            <?php endif; ?>
        </div>
    <?php if ($shippingAddress): ?>
        <div class="col-2" id="shipping-address">
            <h2 class="legend"><?php echo $this->__('Shipping Address') ?></h2>
            <?php echo $this->getChild('shipping')->setFieldNamePrefix('shipping')->setHideEmailAddress(true)->toHtml(); ?>
        </div>
    </div>

    <div class="info-set col2-set">
        <div class="col-2">
            <div class="box paypal-shipping-method">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Method') ?></h3>
                </div>
                <div class="box-content">
                    <?php echo $this->getChild('shipping_method')->toHtml(); ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    </div>

    <div class="info-set">
        <h2 class="legend"><?php echo $this->__('Items in Your Shopping Cart') ?><span class="separator"> | </span><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Shopping Cart') ?></a></h2>
        <div id="details-reload">
            <?php echo $this->getChildHtml('details') ?>
        </div>
    </div>
        <?php echo $this->getChildHtml('agreements'); ?>
        <div class="buttons-set buttons-set-order" id="review-buttons-container">
            <button type="button" id="review_button" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
            <button type="button" id="review_submit" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
            <button type="button" id="update_order" class="button btn-checkout"><span><span><?php echo $this->__('Update Order Data') ?></span></span></button>
            <span class="please-wait" id="review-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
// submit buttons are not needed when submitting with ajax
$('review_submit').hide();
if ($('update_shipping_method_submit')) {
    $('update_shipping_method_submit').hide();
}

<?php if ($this->getUseAjax()):?>
    OrderReviewController.prototype._submitOrder = function() {
        if (this._canSubmitOrder) {
            if (this._pleaseWait) {
                this._pleaseWait.show();
            }
            new Ajax.Request(this.form.action, {
                parameters: {isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {
                    try{
                        response = eval('(' + transport.responseText + ')');
                    } catch (e) {
                        response = {};
                    }
                    if (response.redirect) {
                        setLocation(response.redirect);
                        return;
                    }
                    if (response.success) {
                        setLocation('<?php echo $this->getSuccessUrl()?>');
                        return;
                    } else {
                        var msg = response.error_messages;
                        if (typeof(msg)=='object') {
                            msg = msg.join("\n");
                        }
                        if (msg) {
                            $('review-please-wait').hide();
                            alert(msg);
                            return;
                        }
                    }
                    $('review-please-wait').hide();
                    alert('<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>');
                    return;
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    $('review-please-wait').hide();
                }
            });
        }
    }
<?php endif ?>
PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
    'shipping_method', null, 'details-reload'
);
PayPalExpressAjax.addPleaseWait($('review-please-wait'));
PayPalExpressAjax.setShippingAddressContainer($('shipping-address'));
PayPalExpressAjax.setShippingMethodContainer('shipping-method-container');
PayPalExpressAjax.shippingMethodsUpdateUrl = '<?php echo $this->escapeHtml($this->getUpdateShippingMethodsUrl()) ?>';
PayPalExpressAjax.setUpdateButton($('update_order'),'<?php echo $this->escapeHtml($this->getUpdateOrderSubmitUrl()) ?>','details-reload');
if ($('billing:as_shipping')) {
    PayPalExpressAjax.setCopyElement($('billing:as_shipping'));
}
//]]>
</script>
